### ISSUE TITLE
Guzzle5 has moved to a new package name.

### ISSUE THREAD

**Issue by martinfrances107** [fubhy/graphql-php#1]
Here is the output of 
composer update 

Guzzle 5 has moved to a new package name.

Guzzle 3 is deprecated,

phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
symfony/console suggests installing psr/log (For using the console logger)

**Comment by fubhy** [comment]
This package does not use Guzzle. You are probably running "composer update" in Drupal?

**Comment by martinfrances107** [comment]
Ah thanks my mistake
